//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Permiso { get; set; }
        public string RoleUser { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
